### ISSUE TITLE
Развернуть бекенд на render.com для теста

### ISSUE THREAD

**Issue by fey** [getmentor/getmentor-backend#4]
Нужно попробовать развернуть апи на render.com, тк он бесплатный.
Описать инструкцию по разворачиванию. Будем использовать сервис для развертывания тестового окружения.

**Comment by fey** [comment]
Сделал публичным, Пробуй. Только не занимай имя приложения :) 
ССделай типа aslanav-getmentorbackend

Я ставлю в именах приложений префикс с ником, чтобы не занимать имена.

**Comment by AslanAV** [comment]
Хм... я не могу это сделать, возможно проблема не в публичности, а в том кто создатель репозитория. 
У меня нет возможности выбрать этот репозиторий на render.com/

**Comment by AslanAV** [comment]
если форкнуть то работает)

**Comment by fey** [comment]
Это нормально. Задеплой свой форк. Добавь плз инструкцию, как деплоить

**Comment by AslanAV** [comment]
Добавил [PR](https://github.com/getmentor/getmentor-backend/pull/7)

DEMO-API: https://aslan-getmentor-dev.onrender.com/api/test
вернёт: "test api"

DEMO:  https://aslan-getmentor-dev.onrender.com
вернёт: стартовую страницу Laravel

**Comment by AslanAV** [comment]
DEMO: https://getmentor-original.onrender.com/

API DOC: https://getmentor-original.onrender.com/docs/api#/

**Comment by AslanAV** [comment]
@fey я думаю можно закрыть этот ишью?
